MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "./pretrained_model/R-50.pkl"
  BACKBONE:
    CONV_BODY: "R-50-FPN"
  ATTRIBUTE_ON: False
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
  RPN:
    USE_FPN: True
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TEST: 1000
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 512
    POSITIVE_FRACTION: 0.5
    USE_FPN: True
  ROI_BOX_HEAD:
    NUM_CLASSES: 1601
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
INPUT:
  MIN_SIZE_TRAIN: 600
  MAX_SIZE_TRAIN: 1000
  MIN_SIZE_TEST: 600
  MAX_SIZE_TEST: 1000
DATASETS:
  TRAIN: ("vg_train",)
  TEST: ("vg_val",)
DATALOADER:
  SIZE_DIVISIBILITY: 32
  NUM_WORKERS: 4
SOLVER:
  BASE_LR: 0.0025
  WEIGHT_DECAY: 0.0005
  STEPS: (480000, 640000)
  MAX_ITER: 1520000
  IMS_PER_BATCH: 8
  WARMUP_ITERS: 0
  CHECKPOINT_PERIOD: 10000
OUTPUT_DIR: "./models/obj_faster_rcnn_R_50_FPN_bs8"
DATA_DIR: "./datasets"
USE_TENSORBOARD_LOGS: True