MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "./pretrained_model/R-101.pkl"
  # WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  BACKBONE:
    CONV_BODY: "R-101-C4"
  ATTRIBUTE_ON: False
  RPN:
    PRE_NMS_TOP_N_TEST: 6000
    POST_NMS_TOP_N_TEST: 1000
    ANCHOR_SIZES: (128, 256, 512)
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 256
    POSITIVE_FRACTION: 0.5
  ROI_BOX_HEAD:
    NUM_CLASSES: 1601
  RESNETS:
    RES5_DILATION: 1
INPUT:
  MIN_SIZE_TRAIN: 600
  MAX_SIZE_TRAIN: 1000
  MIN_SIZE_TEST: 600
  MAX_SIZE_TEST: 1000
DATASETS:
  TRAIN: ("vg_train",)
  TEST: ("vg_val",)
SOLVER:
  BASE_LR: 0.0025
  WEIGHT_DECAY: 0.0005
  STEPS: (480000, 640000)
  MAX_ITER: 1520000
  IMS_PER_BATCH: 8
  WARMUP_ITERS: 0
  CHECKPOINT_PERIOD: 10000
DATALOADER:
  NUM_WORKERS: 4
OUTPUT_DIR: "./models/obj_faster_rcnn_R_101_RES_bs8"
DATA_DIR: "./datasets"
USE_TENSORBOARD_LOGS: True