MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "./pretrained_model/R-101.pkl"
  # WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  RPN_ONLY: True
  BACKBONE:
    CONV_BODY: "R-101-C4"
  RPN:
    BATCH_SIZE_PER_IMAGE: 512
    PRE_NMS_TOP_N_TEST: 6000
    POST_NMS_TOP_N_TEST: 1000
    ANCHOR_SIZES: (128, 256, 512)
INPUT:
  MIN_SIZE_TRAIN: 600
  MAX_SIZE_TRAIN: 1000
  MIN_SIZE_TEST: 600
  MAX_SIZE_TEST: 1000
DATASETS:
  TRAIN: ("vg_train",)
  TEST: ("vg_val",)
SOLVER:
  BASE_LR: 0.0025
  WEIGHT_DECAY: 0.0005
  STEPS: (480000, 640000)
  MAX_ITER: 1520000
  IMS_PER_BATCH: 8
  WARMUP_ITERS: 0
DATALOADER:
  NUM_WORKERS: 4
OUTPUT_DIR: "./models/rpn_faster_rcnn_R_101_RES_bs8"
DATA_DIR: "./datasets"
USE_TENSORBOARD_LOGS: True