MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "./pretrained_model/R-50.pkl"
  RPN_ONLY: True
  BACKBONE:
    CONV_BODY: "R-50-FPN"
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
  RPN:
    USE_FPN: True
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TEST: 1000
INPUT:
  MIN_SIZE_TRAIN: 600
  MAX_SIZE_TRAIN: 1000
  MIN_SIZE_TEST: 600
  MAX_SIZE_TEST: 1000
DATASETS:
  TRAIN: ("vg_train",)
  TEST: ("vg_val",)
SOLVER:
  BASE_LR: 0.0025
  WEIGHT_DECAY: 0.0005
  STEPS: (480000, 640000)
  MAX_ITER: 1520000
  IMS_PER_BATCH: 8
  WARMUP_ITERS: 0
DATALOADER:
  NUM_WORKERS: 4
  SIZE_DIVISIBILITY: 32
OUTPUT_DIR: "./models/rpn_faster_rcnn_R_50_RPN_bs8"
DATA_DIR: "./datasets"