MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "./pretrained_model/R-101.pkl"
  # WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  BACKBONE:
    CONV_BODY: "R-101-C4"
  HAS_ATTRIBUTE: False
  RPN:
    BATCH_SIZE_PER_IMAGE: 64
    PRE_NMS_TOP_N_TEST: 6000
    POST_NMS_TOP_N_TEST: 1000
    ANCHOR_SIZES: (128, 256, 512)
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 64
    POSITIVE_FRACTION: 0.5
  ROI_BOX_HEAD:
    NUM_CLASSES: 1601
    NUM_ATTRIBUTES: 401
  RESNETS:
    RES5_DILATION: 1
INPUT:
  MIN_SIZE_TRAIN: 600
  MAX_SIZE_TRAIN: 1000
  MIN_SIZE_TEST: 600
  MAX_SIZE_TEST: 1000
DATASETS:
  TRAIN: ("vg_train",)
  TEST: ("vg_val",)
SOLVER:
  BASE_LR: 0.001
  WEIGHT_DECAY: 0.0005
  STEPS: (350000, )
  MAX_ITER: 380000
  IMS_PER_BATCH: 8
  WARMUP_ITERS: 0
# SOLVER:
#   BASE_LR: 0.002
#   WEIGHT_DECAY: 0.0005
#   STEPS: (175000, )
#   MAX_ITER: 190000
#   IMS_PER_BATCH: 16
#   WARMUP_ITERS: 0
DATALOADER:
  NUM_WORKERS: 4
OUTPUT_DIR: "./models/detection_no_attribute_bs16"
DATA_DIR: "./datasets"